version: '3'
volumes:
    db:
services:
    bibliogram:
        build: .
        image: cloudrac3r/bibliogram
        volumes:
            - db:/app/db
        ports:
            - 10407:10407
        restart: unless-stopped
        networks: 
            - "net"
        environment:
            VIRTUAL_HOST: 0.0.0.0

networks:
    net:
        external: true
