version: '3'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      net:
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      net:
    ports:
      - "0.0.0.0:3000:3000"
    hostname: 'invidious'
    domainname: 'invidious.local'
    environment:
      VIRTUAL_HOST: 'invidious'
      VIRTUAL_PORT: 3000
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: kemal
          host: postgres
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        domain:
    depends_on:
      - postgres

volumes:
  postgresdata:

networks:
  net: